### ISSUE TITLE
Outdated Discord logo

### ISSUE THREAD

**Issue by deffcolony** [Pictogrammers/pictogrammers.github.io#2]
The **mdi-discord** has a outdated logo of discord at:
https://pictogrammers.github.io/@mdi/font/5.4.55/

Screenshot of the discord logo version:

![image]( https://i.imgur.com/3ugx6BD.png)

**Comment by Simran-B** [comment]
We deprecated and removed the Discord icon in [version 7](https://github.com/Templarian/MaterialDesign/issues/6504) in accordance with our brand guidelines (https://github.com/Templarian/MaterialDesign/issues/6564). Please use [SimpleIcons](https://simpleicons.org/) to use this logo.
